### ISSUE TITLE
Missing 'MultiHeadMapAttention' implementation in codebase

### ISSUE THREAD

**Issue by brainstormyyf** [luo3300612/LaRE#3]
File "model.py", line 8, in <module>
from model_base import MultiHeadMapAttention
ImportError: cannot import name 'MultiHeadMapAttention' from 'model_base'
Could you please provide the code for the implementation of MultiHeadMapAttention？I would appreciate it.

**Comment by luo3300612** [comment]
Updated. Please refer to this [link](https://github.com/luo3300612/LaRE/blob/main/model_base.py#L313C7-L313C28).
